In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
dxt = pd.read_csv("./Codefest IIT BHU/train3.csv")
print(dxt.describe)

<bound method NDFrame.describe of                                                 author_id  year  venue_id  \
0       [302080, 254034, 1650574, 1688060, 356214, 144...  2011     15632   
1                                                [471182]  2010     15752   
2                                               [1252574]  2012     19098   
3           [1700521, 1634966, 1560119, 1588537, 1657765]  2012     20323   
4                                       [750555, 1125222]  2010     12539   
5                                               [1113314]  2011     13076   
6                     [1687401, 1695935, 1351136, 406300]  2010     12718   
7                                               [1559624]  2013     23853   
8                                                [893313]  2010     13523   
9                                       [787613, 1520291]  2013     18753   
10                                     [1484595, 1579993]  2011     14977   
11                   [1266444, 1622482, 16

In [4]:
dxxt = dxt.values
print(dxxt[10])

['[1484595, 1579993]' 2011 14977 12 276249]


In [5]:
dxxt.shape

(222000, 5)

In [51]:
Y_val = []
for i in range(100):
    r = np.random.randint(222000)
    zzz = dxxt[r,3]
    Y_val.append(zzz)
print(Y_val)
    

[0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 5, 10, 0, 0, 0, 13, 7, 0, 16, 37, 0, 4, 19, 2, 0, 0, 0, 4, 7, 12, 7, 8, 0, 1, 18, 2, 0, 13, 0, 0, 24, 0, 0, 5, 0, 0, 14, 0, 13, 0, 0, 8, 0, 0, 0, 0, 1, 24, 0, 41, 0, 0, 7, 8, 15, 0, 0, 1, 0, 8, 8, 1, 0, 12, 31, 7, 26, 0, 32, 0, 0, 0, 8, 0, 0, 0, 21, 8, 25, 0, 32, 21, 9, 0, 0, 0, 12, 2, 6]


In [38]:
Y_train=Y_train.astype('int')
Y_train = dxxt[:,3]
print(Y_train)

[0 0 0 ... 21 0 9]


In [7]:
new_drop = dxt.drop(columns=['citations', 'author_id'])
print(new_drop.head)

<bound method NDFrame.head of         year  venue_id      id
0       2011     15632  162253
1       2010     15752   42448
2       2012     19098  226093
3       2012     20323  281211
4       2010     12539    8973
5       2011     13076  109597
6       2010     12718   70652
7       2013     23853  267367
8       2010     13523   67799
9       2013     18753  366200
10      2011     14977  276249
11      2010     21916   18269
12      2011      1769  146521
13      2012      5884  183907
14      2013     20048  316015
15      2011     22278  181001
16      2010      8987   84322
17      2013     20175  309362
18      2012      6257  259915
19      2010     15850   17615
20      2012     15632  208947
21      2010     10292   53960
22      2012      2010  250840
23      2012     13337  296234
24      2010     21605   31329
25      2010     25315  182434
26      2013     12659  360685
27      2010     13342   66536
28      2011       757  323325
29      2012     12730  240591
...      

In [8]:
new_drop_dxxt = new_drop.values
print(new_drop_dxxt[10])

[  2011  14977 276249]


In [9]:
X_train = new_drop_dxxt[:,]
print(X_train[10])

[  2011  14977 276249]


In [11]:
xtest = pd.read_csv("./Codefest IIT BHU/test3.csv")
print(xtest.head)

<bound method NDFrame.head of                                    author_id  year  venue_id      id
0                                  [1138048]  2010     22698   77152
1                         [1111668, 1154294]  2012      1037  253904
2                         [1505756, 1382981]  2010     22438   46386
3                           [634857, 542921]  2010     21723   19572
4        [1709244, 1240251, 490730, 1525100]  2012     22453  182480
5                          [1502781, 689925]  2010      7188   53798
6                           [1430553, 51892]  2013     15683  319027
7                          [1176134, 382560]  2011      2825  323322
8                                   [922724]  2010     22399   52550
9        [585718, 1036888, 1576918, 1605696]  2012      2188  243774
10                        [1458012, 1600262]  2010      6481   10152
11                                 [1480345]  2012      5153  203538
12                        [1361431, 1298617]  2011     20130  153095
13  

In [12]:
xtest = xtest.drop(columns='author_id')

In [13]:
X_test= xtest.values
print(X_test.shape)

(148144, 3)


In [14]:
print(X_test[1,2])

253904


# SVM ALGO

In [39]:
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='polynomial') # Linear Kernel

In [40]:
# Y_train = Y_train.reshape(-1,1)
# print(Y_train)

In [41]:

#Train the model using the training sets
clf.fit(X_train, Y_train)

ValueError: Unknown label type: 'unknown'

In [42]:
from sklearn import svm
#from mlxtend.plotting import plot_decision_regions

clf = svm.SVC(decision_function_shape = 'ovo')
clf.fit(X_train, Y_train) 

ValueError: Unknown label type: 'unknown'

In [52]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [53]:
def hypothesis(x,theta):
    return sigmoid(np.dot(x,theta))

In [54]:
def error(Y,X,theta):
    m = X.shape[0]
    total_error = 0.0
    
    for i in range(m):
        y_hat = hypothesis(X[i],theta)
        total_error += (Y[i]*np.log2(y_hat)+(1-Y[i])*np.log2(1-y_hat)) 
        
    return total_error/m #Average Loss

In [55]:
def get_grad(Y,X,theta):
    
    grad = np.zeros(theta.shape)
    m = X.shape[0]
    for i in range(m):
        y_hat = hypothesis(X[i],theta)
        x = X[i].reshape((-1,1))
        grad += (Y[i] - y_hat)*x
        
        
    return grad/m #Average Gradient

In [56]:
def grad_descent(X,Y,learning_rate=0.5):
    theta = np.zeros((X.shape[1],1))
    
    error_list = []
    
    for i in range(500):
        theta = theta + learning_rate*get_grad(Y,X,theta)
        e = error(Y,X,theta)
        error_list.append(e)
        
    return theta,error_list

In [58]:
# theta,error_list = grad_descent(X_train,Y_train)

In [115]:
from sklearn.ensemble import GradientBoostingRegressor
GBR = GradientBoostingRegressor(n_estimators=200, max_depth=11)


In [116]:
GBR.fit(X_train, Y_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.1, loss='ls', max_depth=11,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [108]:
y_pred_random = GBR.predict(X_test)

In [109]:
print(y_pred_random)

[ 2.98202471e+00  1.50377677e+01  8.37805360e+00 ... -2.68878872e-02
  2.92076370e+01  1.30649044e-01]


In [110]:
outcome1 = {'id':[], 'citations':[]}

In [111]:
for i in y_pred_random:
    z = i
    outcome1['citations'].append(z)

In [112]:
for i in range(X_test.shape[0]):
    zz = X_test[i,2]
    outcome1['id'].append(zz)

In [113]:
print(outcome1["citations"])

[2.982024713154113, 15.037767672207574, 8.378053600273489, 15.09964847927037, 7.5297006163003815, 8.508046439109053, 5.086467030662405, 0.1815021741680396, 5.7047768561526455, 5.7785657902804095, 5.211481788856385, 0.3056507099643767, 7.850468638805347, 13.751816072262416, 1.551024903696144, 10.760400151923399, 4.217089818052445, 0.0436593992274495, -0.005775924721408214, 0.6046981653473203, 9.715045326158362, -0.05197301639603804, -0.005775924721408214, 34.68146495354134, 1.4738541745862634, 0.06910515967983255, 0.8726128465639967, 2.146516134686226, -0.01650028273613543, 3.965738969096401, 4.827903845786514, 11.220042702359345, 0.19434702200420406, 0.22175852291306444, 0.7737736562987872, 3.1516911304775608, 5.506400535229866, -0.1604606378291153, -0.005775924721408214, 8.11694778604494, 0.5817119072656681, 6.945285736393432, 1.4076327535178754, 6.693854435697639, 4.205355846448291, 2.275336208118966, 0.03300530275923779, 6.157233406297633, 9.784840644745623, 0.08086903425158508, 4.3

In [114]:
people3 = pd.DataFrame(outcome1)
people3.to_csv('./Codefest IIT BHU/prediction_new_random3.csv' , index=False)

# Nueral Network

In [43]:
# Build Our Neural Network Problem
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
from keras import backend as K


Using TensorFlow backend.


In [44]:
def r2_score(y_true, y_pred):
  
  #y_true = np.array(y_true)
  #y_pred = np.array(y_pred)
  
  num = K.sum(K.square(y_true-y_pred))
  denom = K.sum(K.square(y_true - K.mean(y_true)))
  return(1-num/denom)


def getModel():
  model = Sequential()
  model.add(Dense(64, activation = "relu", input_shape = (13, )))
  model.add(Dense(32, activation = "relu"))
  model.add(Dense(1))
  
  model.compile(optimizer = "adam", loss = "mse", metrics = [r2_score])
  
  return model

In [45]:
model = getModel()
model.summary()

W0825 12:58:27.576300  4724 deprecation_wrapper.py:119] From c:\users\ramesh\appdata\local\programs\python\python37\lib\site-packages\keras\backend\tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0825 12:58:27.626271  4724 deprecation_wrapper.py:119] From c:\users\ramesh\appdata\local\programs\python\python37\lib\site-packages\keras\backend\tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0825 12:58:27.634267  4724 deprecation_wrapper.py:119] From c:\users\ramesh\appdata\local\programs\python\python37\lib\site-packages\keras\backend\tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

W0825 12:58:27.901115  4724 deprecation_wrapper.py:119] From c:\users\ramesh\appdata\local\programs\python\python37\lib\site-packages\keras\optimizers.py:790: The name tf.train.Optimizer is deprecated. Please use

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 64)                896       
_________________________________________________________________
dense_2 (Dense)              (None, 32)                2080      
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 33        
Total params: 3,009
Trainable params: 3,009
Non-trainable params: 0
_________________________________________________________________


In [47]:
hist = model.fit(X_train, Y_train, verbose = 1, validation_data = (Xt, Yt) , epochs = 30)

ValueError: Error when checking input: expected dense_1_input to have shape (13,) but got array with shape (3,)